name: Camel Version CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  camel:
    strategy:
      fail-fast: false
      matrix:
        camel-version: [ "4.4.5", "4.8.3", "4.0.0.redhat-00036", "4.4.0.redhat-00046", "4.8.0.redhat-00017"]
    timeout-minutes: 30

    env:
      CODE_VERSION: max
      CODE_TYPE: stable
      TEST_RESOURCES: test-resources
      CAMEL_VERSION: ${{ matrix.camel-version }}

    runs-on: ubuntu-latest
    name: ${{ matrix.camel-version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Add Red Hat Maven GA repository to settings.xml for 4.8.0 productized
        uses: s4u/maven-settings-action@v3.1.0
        if: ${{ startsWith(matrix.camel-version, '4.8.0') }}
        with:
          repositories: '[{"id":"redhat.ga","name":"Red Hat Maven repository GA","url":"https://maven.repository.redhat.com/ga"}]'
          pluginRepositories: '[{"id":"redhat.ga","name":"Red Hat Maven repository GA","url":"https://maven.repository.redhat.com/ga"}]'
          
      - name: Check settings.xml created
        run: cat ~/.m2/settings.xml

      - name: Install JBang ubuntu
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo "$HOME/.jbang/bin" >> $GITHUB_PATH

      - name: Setup JBang (trusted sources)
        run: jbang trust add https://github.com/apache/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install global dependencies
        run: npm install -g typescript @vscode/vsce

      - name: npm-ci
        run: npm ci

      - name: Allow unprivileged user namespace (ubuntu)
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: ui test
        id: uiTest
        run: xvfb-run --auto-servernum npm run ui-test

      - name: vsce package
        run: vsce package

      - name: Store UI test log
        uses: actions/upload-artifact@v4
        if: |
          (failure() || cancelled()) &&
          (steps.uiTest.outcome == 'failure' ||
          steps.uiTest == 'cancelled')
        with:
          name: ${{ matrix.camel-version }}-ui-test-logs
          path: test-resources/settings/logs/*

      - name: Store UI Test Screenshots
        uses: actions/upload-artifact@v4
        if: |
          (failure() || cancelled()) &&
          (steps.uiTest.outcome == 'failure' ||
          steps.uiTest.outcome == 'cancelled' )
        with:
          name: ${{ matrix.camel-version }}-ui-test-screenshots
          path: test-resources/screenshots/*.png

  check:
    if: always()
    runs-on: ubuntu-latest
    name: Status Check
    needs: [ camel ]
    steps:
      - name: Test Matrix Result
        run: |
          echo result = ${{ needs.camel.result }}
      - name: Status Check - success
        if: ${{ needs.camel.result == 'success' }}
        run: |
          echo "All tests successfully completed!"
          exit 0
      - name: Status Check - failure
        if: ${{ needs.camel.result != 'success' }}
        run: |
          echo "Status Check failed!"
          exit 1
